### ISSUE TITLE
[Bug] .NETstandart 2.0 Unable to make the shared transition animation appear

### ISSUE THREAD

**Issue by Phenek** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#1]
## Bug Information
Unable to make animation appear, I still got the native navigation with Slide effect on IOS and Fade effect on Android.

### Steps to reproduce the Behavior
I tried to load the repository even if I build the sharedTransition project , I got a : 
"SharedTransitions/bin/Debug/netstandard2.0/Plugin.SharedTransitions.dll' could not be found"

Cause the sharedTransition project got a .netstandarLibrairy to 1.6.1 and the sample got 2.0.3.

Looks awesome anyway 👍 

I'm on Mac with last Xamarin.forms Release.
Regards,

**Comment by GiampaoloGabba** [comment]
Hello, thanks for your feedback.
Next week i'm going to put some efforts in this plugin :)

**Comment by Phenek** [comment]
Always watching
Let me know ;)

**Comment by Phenek** [comment]
Regarding my fork, [here](https://github.com/Phenek/Xamarin.Plugin.SharedTransitions)
I was able to make the sample works on iOS.

But on Android I got an exception "Unknown scene name: pathInterpolator"
when creating transition from xml = > transitionInflater.InflateTransition(Resource.Transition.navigation_transition);

Also I was unable to make the transition works from a ListView

If you could take a look, it would be very nice,
Sorry to bother you.
regards.

**Comment by GiampaoloGabba** [comment]
Sorry, i was busing working on zxing.mobile and android to make ti work better, hopefully i will be able to update this plugin in the next few days

**Comment by maxyhi** [comment]
hey, is there an update on this issue?

**Comment by GiampaoloGabba** [comment]
Hello,
i'm close to release a new version that fix the .NETStandard issue and enables transitions also on layouts (boxview, frame, ecc...) i just need to fix a couple of things in ios.
Plus there are some minor bigufixes and enhancements.

I hope tu pubblish everything before mid july

**Comment by GiampaoloGabba** [comment]
the latest commit address the .net standard issue. i'll pubblish a new nuget very soon
