### ISSUE TITLE
Crash when the image does not exist.

### ISSUE THREAD

**Issue by rudacs** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#10]
## Bug Information

Version Number of Plugin: 2.0.1
Device Tested On: iPhone X
Simulator Tested On: iPhone X
Version of VS: 8.2.3
Version of Xamarin: 12.14.0.114
Versions of other things you are using:

### Steps to reproduce the Behavior
Create Image and set image does not exist (local or remote).

### Expected Behavior
No crash. And continue the animation.

### Actual Behavior
Crash.

### Error
System.NullReferenceException: Object reference not set to an instance of an object
  at Plugin.SharedTransitions.Platforms.iOS.ViewExtensions.GetImageFrame (UIKit.UIImageView imageView)

**Comment by GiampaoloGabba** [comment]
well, good find! I havent tested with nonexisting images. I will fix this, in the meantime i suggest to use existing images :)

**Comment by GiampaoloGabba** [comment]
This is fixed in master branch. I'll pubblish a new nuget when i'll fix the pop transition duration in issue #11 
Thank you for your report!

**Comment by rudacs** [comment]
Thanks for this amazing component.  I found out that I didn't put the image in the project.
