### ISSUE TITLE
DataTemplate in ListView

### ISSUE THREAD

**Issue by mkgitalia** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#14]
Version Number of Plugin:2.0.2
Device Tested On: Samsung SM-G935F
Version of VS: 16.2.3
Version of Xamarin: 4.2.0.709249
Versions of other things you are using: Prism.Unity.Forms 7.2.0.1367

I want use your plugin with a **DataTemplate** inside a **<ContentPage.Resources>  <ResourceDictionary>** (because I want use an AlternateColorDataTemplateSelector) but VS break with this error message "**System.InvalidOperationException:** 'Shared transitions effect can be attached only to element in a SharedNavigationPage'"

Can you help me ? thanks

**Comment by GiampaoloGabba** [comment]
Hello, it seems that the plugin is not finding the upper SharedTransitionNavigationPage wich should incapsulated your page. 
If you can send me a reproduction link or a xaml example i'll take a look

**Comment by mkgitalia** [comment]
[PiedeMail.png]


   Da "Giampaolo Gabba" notifications@github.com
   A "GiampaoloGabba/Xamarin.Plugin.SharedTransitions" Xamarin.Plugin.SharedTransitions@noreply.github.com
   Cc "beppe fasano" beppe@beppefasano.it,"Author" author@noreply.github.com
   Data Sat, 24 Aug 2019 07:59:40 -0700
   Oggetto Re: [GiampaoloGabba/Xamarin.Plugin.SharedTransitions] DataTemplate in ListView (#14)

   Hello, it seems that the plugin is not finding the upper SharedTransitionNavigationPage wich should incapsulated your page.
   If you can send me a reproduction link or a xaml example i'll take a look

**Comment by hjavaher** [comment]
Did you by any chance find the solution to this problem? I'm having the same issue

**Comment by GiampaoloGabba** [comment]
This is fixed in the next version coming very soon :)
