### ISSUE TITLE
Exception on sharedTransitions: Transition.Group. Can Help? 

### ISSUE THREAD

**Issue by FelipeOsti** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#15]
I am encountering the exception "System.MissingMethodException: 'Default constructor not found for type Plugin.SharedTransitions.Platforms.Android.TransitionEffect'"
The above Exception is triggered when I add the shared transaction to: 
```
"<pancakeview:PancakeView Margin =" 15,0,0,5 "Elevation =" 2 "
                                                 IsClippedToBounds = "True"
                                                 HorizontalOptions = "FillAndExpand"
                                                 CornerRadius = "50,0,50,0"
                                                 BackgroundColor = "{Binding color}"
                                                 sharedTransitions: Transition.Group = "{Binding ID}"
                                                 sharedTransitions: Transition.Name = "Opportunity"> "
```

**Comment by GiampaoloGabba** [comment]
Does your linker is set to "link all" ?
Is the plugin installed in all projects?
It would be helpful to have a sample project that reproduces this behaviour so i can take a look at it

**Comment by GiampaoloGabba** [comment]
Haven't heard any response in 25 days, closing this.
If you have further question dont heasitate to open another issue.
