### ISSUE TITLE
How to use with the new shell feature in XF4+?

### ISSUE THREAD

**Issue by biapar** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#18]
How to use with the new shell feature in XF4+?

**Comment by GiampaoloGabba** [comment]
Actually shell support is working in the relative branch, i just didnt have time to finish the work and pubblish a new nuget.

Now that in Italy the work are slowing down a bit i'm planning to revive this project!

**Comment by GiampaoloGabba** [comment]
Hello, this is coming with with the next version coming very soon, i have already pushed it to the main branch
