### ISSUE TITLE
[Question] Does this work with PopupPage?

### ISSUE THREAD

**Issue by mzhukovs** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#19]
Before I give this a stab - wanted to ask the question first: can these transitions be used between a regular Page and a PopupPage (e.g. Prism.Plugin.Popups [which relies on Rg.Plugins.Popups])? 

Please let me know if anyone has done this successfully, thank you.

**Comment by GiampaoloGabba** [comment]
Nope sorry, it can work only in a NavigationPage (or shell).
As far as i know there is no way to make it work wit ha popup page (so a page outside the navigation stack)
