### ISSUE TITLE
Works on images and buttons only, not on custom views/frames/layouts

### ISSUE THREAD

**Issue by technololy** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#2]
Nice plugin. I have been trying it since yesterday. and i can only get it to work with images and buttons. Is this the intended action?

**Comment by GiampaoloGabba** [comment]
Yep, i'm unable to make it works with layouts (stacklayout, frame, ecc...). It works only with controls like labels, buttons, images, inputs.
I need to investigate further but for the first release i focused on the "simplier" stuff :)

**Comment by GiampaoloGabba** [comment]
So a lot of time is passed since this issue. This plugin now supports animations between layouts
