### ISSUE TITLE
Support for UWP?

### ISSUE THREAD

**Issue by RyanGaudion** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#20]
Is there a plan to support UWP, if so how long until we can expect this feature?

**Comment by GiampaoloGabba** [comment]
UWP support is not in my plan, basically because o dont know nothing about UWP and i dont have time to learn it, this is the sad truth :(

But if someone expert in UWP want to make a PR i will be super hapèpy to help!

**Comment by mhrastegari** [comment]
> UWP support is not in my plan, basically because o dont know nothing about UWP and i dont have time to learn it, this is the sad truth :(
> 
> But if someone expert in UWP want to make a PR i will be super hapèpy to help!

Hope this helps 👇 cuz i really like to use your plugin in UWP too :(
https://docs.microsoft.com/en-us/windows/communitytoolkit/animations/connectedanimations

**Comment by GiampaoloGabba** [comment]
While i dont have time to support this, i will be superhappy if someone expert in uwp can help with a pull request :)

**Comment by Strypper** [comment]
UWP already have the native Connected Animation you can use that

**Comment by craigwi** [comment]
I created a first attempt at UWP support in my fork: https://github.com/craigwi/Xamarin.Plugin.SharedTransitions.  The UWP Sample app appears to work with one significant issue: CachedImage renderer does not have a size when first loaded (even though the Xamarin Forms element does) and so the animation shows the image disappearing.

Lots of details to figure out.  I would be happy to create a pull request here (e.g., to an alternate branch) or to entertain PR in my fork.

**Comment by GiampaoloGabba** [comment]
hello @craigwi 
A pull request would be wonderful! So i can test it and maybe we can see toegheter some details :)

**Comment by GiampaoloGabba** [comment]
Good news everyone :)
I started to work on UWP, for now the results are too unstable even for a preview. 
To fix this i opened 2 pull requests in the Xamarin.Forms repo that will allow me to jump in the navigation process inside the renderer and make things rock solid!

The code itself for the SharedTransitions is quite trivial, i just need the right nagivation hooks to execute it, otherwise is a big party of "access violation" errors :)

I everything goes well we will have uwp shared transitions with Xamarin.Forms 5.

https://github.com/xamarin/Xamarin.Forms/pull/12439
https://github.com/xamarin/Xamarin.Forms/pull/12442

**Comment by MuleaneEve** [comment]
Hi,
Any news regarding this feature?
I'm looking forward to using it in the UWP version of my app.

**Comment by bruzkovsky** [comment]
@GiampaoloGabba this sounds very good! Do you already have a branch were you are developing this? I'd really like to check this out!

**Comment by Agredo** [comment]
@GiampaoloGabba if you want help I would help you too. It seems your Xamarin.Forms issues are already merged.

**Comment by GiampaoloGabba** [comment]
Closing this, i'm going to support WinUI in maui, i will not add new features to the xforms version

**Comment by Agredo** [comment]
This is sad because WinUI is not really a alternatve for UWP (for another one or two years). There are to many missing functioanlities and performance issues.
