### ISSUE TITLE
Does not seem to be compatible with new AndroidX versions of Forms

### ISSUE THREAD

**Issue by RedChops** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#23]
## Bug Information

Version Number of Plugin: 2.0.2
Device Tested On: Pixel 2 Emulator
Simulator Tested On: iOS 13 simulator
Version of VS: 2019 16.4.4
Version of Xamarin: 4.6.0.240-nightly
Versions of other things you are using:

### Steps to reproduce the Behavior
* Have the above versions of the software.
* Try to build the solution
### Expected Behavior
Builds without fail
### Actual Behavior
Fails with:
Can not resolve reference: `Xamarin.Android.Support.Fragment`, referenced by `Plugin.SharedTransitions`. Please add a NuGet package or assembly reference for `Xamarin.Android.Support.Fragment`, or remove the reference to `Plugin.SharedTransitions`.	ContractPlanner.Android			

I don't know if this project is still active, it's not seeming so, but I can't build my solution with this plugin in it anymore.

**Comment by RedChops** [comment]
I know that I could add the assembly reference as specified above, but that doesn't make sense, as I don't use it in my application anywhere.

**Comment by GiampaoloGabba** [comment]
In the next few week i'll pubblish a new, updated, version that will target androix library, along with shell support. I'm going to have some free time to dedicate some more love to this puppy :)

**Comment by vunhutien** [comment]
Waiting for your release to support AndroidX and Tabpage, this puppy is so nice.

**Comment by GiampaoloGabba** [comment]
I have a working branch with multitargeting to androidX (using xf 4.5 and target api 29):
[here](https://github.com/GiampaoloGabba/Xamarin.Plugin.SharedTransitions/tree/androidx)

I'm doing some test, if everything is ok i'll release a new version very soon

**Comment by GiampaoloGabba** [comment]
[I have pubblished a pre-release nuget](https://www.nuget.org/packages/Xamarin.Plugin.SharedTransitions/2.1.1-beta) with Android X support.

To enable AndroidX support, use Xamarin.Forms 4.5+ and target API29.

This is my first AndroidX port, so i will leave it in pre-release for a few days, considering that the new version will still support Xaamarin.Forms 4.3 with old Android api (without AndroidX support, of course). I have to be sure that both functionalities (with androidx and without) are the same.

**Comment by GiampaoloGabba** [comment]
Going to pubblish a new release with AndroidX & other fixes very soon
