### ISSUE TITLE
problem in not mvvm project

### ISSUE THREAD

**Issue by maiconalvesdev** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#29]
I have a normal project that is not using mvvm, only model view, when entering the screen I get the error below, I'm using version 2.10 and xamarin.forms 4.5.0.617 the link to the page code is below, I'm using with listview.
error
shared transitions effect can be attached only to element in a ISharedTransitionContainer
page code
https://gist.github.com/maiconalvesdev/10f36aba29d05b56bd0abfcda212c454

**Comment by maiconalvesdev** [comment]
i found the problem, i using master page with detail, @GiampaoloGabba you can help me?

**Comment by GiampaoloGabba** [comment]
Shared Transitions can only works on pages that are inside a `SharedTransitionShell ` or `SharedTransitionNavigationPage`

If you are using shell, you have to replace it with a `SharedTransitionShell ` like [this example](https://github.com/GiampaoloGabba/Xamarin.Plugin.SharedTransitions/blob/master/src/Sample/TransitionShellApp/TransitionShellApp/AppShell.xaml)

If you are not using shell, make sure that your ContentPage is opened inside a `SharedTransitionNavigationPage`, for example doing something like this in your App.xaml.cs

`MainPage = new SharedTransitionNavigationPage(new ListagemMedicos());`

**Comment by GiampaoloGabba** [comment]
I have done a lot of fixes for `MasterDetailPage` and i'm going to pubblish a new release. 
Closing this cause i havent received any feedback
