### ISSUE TITLE
Tag views from code

### ISSUE THREAD

**Issue by ozmica** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#3]
Hi,
awesome work! Is it possible to tag views from code behind?

**Comment by Phenek** [comment]
There is an exemple:

_image is your Xamarin Forms Element.
```
Transition.SetTag(_image, TagValue);
Transition.SetTagGroup(_image, TagGroupValue);
```

**Comment by GiampaoloGabba** [comment]
Already answered by @Phenek , thank you!
