### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by Suplanus** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#33]
Xamarin.Forms.MacOs would be great 💕

**Comment by GiampaoloGabba** [comment]
Sorry, i have time to support only iOS and Android :( 
I will be superhappy to receive a pr, tho. Maybe someone expert in macOS can help and create a pull request' :)

The fact is that ios/macos does not support shared transitions out of the box. So is very time consuming to create them by hand

**Comment by GiampaoloGabba** [comment]
So i changed my mind with this. As soon as the UWP implementation is done i will start with MacOS.
The plan is to support more platform possible and the switch everything to the [XamarinCommunityToolkit](https://github.com/xamarin/XamarinCommunityToolkit) if they want my messy code :)

**Comment by GiampaoloGabba** [comment]
Closing this, i'm going to support Mac Catalyst in maui, i will not add new features to the xforms version
