### ISSUE TITLE
Sample for bindable layout

### ISSUE THREAD

**Issue by sarthak1995-26** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#35]

**Comment by GiampaoloGabba** [comment]
using this plugin with `BindableLayout` is the same as `ListView` and `CollectionView`.

Inside your `DataTemplate` you have to specify a unique combination for: `sharedTransitions:Transition.Name` and `sharedTransitions:Transition.Group`

Maybe in the next release i will update the demo to include a `BindableLayout` :)
