### ISSUE TITLE
[Request] Events for animations

### ISSUE THREAD

**Issue by Inrego** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#39]
I'd love to get some kinds of events/notifications of animation started/ended. This helps to synchronize other animations to run at the same time, and to handle any other animations we might want to do after the transition ends.

**Comment by GiampaoloGabba** [comment]
this is a good suggestion, it will be implemented in the next update!
Currently i'm busy finishing my healthkit/googlefit plugin, when is done i'll implement this, should be fairly easy

**Comment by Inrego** [comment]
Sounds good! I've tried to test different page lifetime events in order to try to synchronise another animation, but none of them are quite at the same time as you start the animation, so it's not quite there yet.

**Comment by GiampaoloGabba** [comment]
this is in the master branch, nuget will come soon :)
