### ISSUE TITLE
Complex example and button animation

### ISSUE THREAD

**Issue by thomashoef** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#4]
The button animation currently does not seem to work any longer.

Would it be possible to add a sample listview to detail view working animation. It does not seem to work any longer on views other than image, or is that assumption incorrect? Thanks!

**Comment by GiampaoloGabba** [comment]
i'm looking in the button animation, it should work.

Regarding a complex example there is an update in the readme with a link to a functional example made by jsuarezruiz

**Comment by GiampaoloGabba** [comment]
Hello, i double checked button animations and are working fine, if you still have issues please post your code so we can try to find the culprit
