### ISSUE TITLE
Can I use this with a CarouselPage

### ISSUE THREAD

**Issue by JMNewsome** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#41]
I typicallly use a carousel page within my app and being able to animate between page changes would be very ideal

**Comment by GiampaoloGabba** [comment]
Shared transitions can only work when there is a parent navigation controller that "orchestrate" the navigation between two pages.
In addition the carouselpage has been superseded by the carouselview and i doubt that will be ported to .net MAUI.

I investigated a bit and found some custom components on android that support this, but still nothing for iOS.
I leave the issue open in the case i will find some trick to make it work with carouselview but i dont promise nothing :)

**Comment by JMNewsome** [comment]
Thank you, I would love to be able to use that instead

**Comment by GiampaoloGabba** [comment]
sadly this could be supported in tabbed pages. i stopped adding new features to this plugin, i'm porting everything to MAUI, new development will be for the new platform :)
