### ISSUE TITLE
BackgroundAnimation Easings

### ISSUE THREAD

**Issue by taublast** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#42]
How difficult would it be to implement easings to BackgroundAnimation please?
Thanks!

**Comment by GiampaoloGabba** [comment]
ummm... in ios should be easy, i have to check in Android cause i'm using background animations declared in xml and i dont like them much (for example cant modify duration). i'll take a look!

**Comment by GiampaoloGabba** [comment]
this plugin is now in maintenance mode, new features will be developed only for the MAUI version
