### ISSUE TITLE
TransitionListenerAdapter and NavigationTransitionListener classes not found exception with v2.3

### ISSUE THREAD

**Issue by toverux** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#43]
## Bug Information

Version Number of Plugin: 2.3
Device Tested On: Multiple Android devices ≤ API 25
Simulator Tested On: Multiple Android simulators ≤ API 25
Version of Xamarin: 4.8

### Steps to reproduce the Behavior

Just use the package on an Android device running an Anroid API lower than 26, version where the missing class was added.
Devices running API 26 onwards have no issues.

### Expected Behavior

No exceptions, like in version 2.2 an prior. Rollbacking to version 2.2 fixes the problem.

### Actual Behavior

Starting from version 2.3, the following exception occurs and the app crashes : https://gist.github.com/toverux/c6cb85da2f41cb0fc64a574632360087

**Comment by GiampaoloGabba** [comment]
thank you for the report!
Wow... this is unexpected :( Maybe api 25 and lower does not support the listener, i have to check.

Do you confirm that the error is here even when the linker is disabled?

**Comment by toverux** [comment]
Hi, thanks for your answer! Yes, the exception also occurs with linking disabled.

**Comment by ramonbrbs** [comment]
Thanks for this report. I'm having same problem here.
Also downgraded to 2.2 and it's working fine.

**Comment by GiampaoloGabba** [comment]
welp... i wasn't using the support libraries for the listener!
Fixed in the next release
