### ISSUE TITLE
[Bug] Frame doesn't respect CornerRadius in transition

### ISSUE THREAD

**Issue by vniehues** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#46]
The frame control seems to ignore its CornerRadius during a transition.
I ran the SampleApp with XF 4.8.0.1269. I know that Frames are kinda f***ed within XF itself at the moment but i still wanted to raise awareness and see, if you can fix this issue rather easily. 
If you cannot do that however, a future XF update might resolve this issue again.
It might also be helpful to report this issue to the XF issue tracker. I have not done this yet.

## Bug Information
Version Number of Plugin: 2.3
Device Tested On: iPhone 11 Pro, iOS 14b5
Simulator Tested On: iOS, multiple
Version of Xamarin: 4.8.0.1269

### Steps to reproduce the Behavior
run sample app.

### Expected Behavior
the frames CornerRadius animates to its chosen value during transition.

### Actual Behavior
the frames CornerRadius seems to be 0 during transition and is snapping back to the chosen value after the transition.

### Screenshots
![iPhone-11-Pro-iOS-13 6-2020-08-30-17-41-20](https://user-images.githubusercontent.com/28765921/91663371-a2a11780-eae8-11ea-9c71-b0358bc30288.gif)

**Comment by GiampaoloGabba** [comment]
probably they modified how the corner radius are managed in the Frame component. I'll take a look

**Comment by vniehues** [comment]
Thanks for the quick answer! 
I only see this behavior in iOS, which means you're probably right about the modification.

**Comment by GiampaoloGabba** [comment]
fixed in the next version
