### ISSUE TITLE
[Enhancement] Allow wrapping TabbedPages in one SharedNavigationPage instead of wrapping the individual pages.

### ISSUE THREAD

**Issue by vniehues** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#47]
I currently can't get the following code to work and I would like to spark a discussion about this.
I don't know, if my request is even possible but if it's not I'd like to get an explanation as to why. 

**xaml tabbed page**

```
<TabbedPage.Children>
        <Page1 Title="Page1">
        </Page1>
        <Page2 Title="Page2">
        </Page2>
</TabbedPage.Children>
```
**navigation**

```
await NavigationService.NavigateAsync("SharedTransitionNavigationPage/TabbedPage");
```
**navigation stack**

```
SharedTransitionNavigationPage/TabbedPage?selectedTab=Page1/Page2
```

### Current State
Currently the navigation and transition happen _inside_ the TabbedPage.
The navigation stack looks like this:

TabbedPage?selectedTab=SharedTransitionNavigationPage/Page1/Page2

### Desired State
Allow the navigation and transition happen _outside_ the TabbedPage.
The navigation stack would look like this:

SharedTransitionNavigationPage/TabbedPage?selectedTab=Page1/Page2

### Justifications
This would allow deep-linking without having to worry about putting a NavigationPage in the right place.
Also, this would clean the code inside the TabbedPage.

Thanks in advance! :)

**Comment by GiampaoloGabba** [comment]
i'll take a look at this after the next version wich will fix some bugs :)

**Comment by GiampaoloGabba** [comment]
this plugin is now in maintenance mode, new features will be developed only for the MAUI version
