### ISSUE TITLE
NullReferenceException on iOS

### ISSUE THREAD

**Issue by jmkyarrow** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#48]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information
StackTrace: at Plugin.SharedTransitions.Platforms.iOS.Renderes.SharedTransitionPageRenderer.Dispose

Version Number of Plugin: latest
Device Tested On: iPhone 6s and iPhone 8 
Version of VS: latest
Version of Xamarin: latest stable

This is just happening when performing some normal navigation that works fine on Android.
If I'm being stupid can somebody let me know ASAP I have a tight deadline on this project.
Will disable the library for now while I do other testing.
If it's an error with the library can we have a fix ASAP please.
Sorry, bit stressed atm.

**Comment by GiampaoloGabba** [comment]
i'm planning an update for this weekend, i think they changed something in the latest versions i have some problems with frames too.

i already fixed this and pushed to the master branch, i need to make some test and maybe i can pubblish it tomorrow

**Comment by GiampaoloGabba** [comment]
new version should be available today
