### ISSUE TITLE
Crash on ShellGoToAsync(../) in Android with Xamarin latest version 

### ISSUE THREAD

**Issue by sarthak1995-26** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#49]
When using SharedTransistion inside shell (<sharedTransitions:SharedTransitionShell) going back from any page causes an exception with message. No view found for id for fragment Shell Fragment Container even if the current page does not have any shared transition usage just replaced Shell with sharedTransitions:SharedTransitionShell

 Exception message :: No view found for id for fragment Shell Fragment Container

When I removed SharedTransition back navigation works fine. Also It only crashes on Android,iOS works fine.

Xamarin.Forms version : Latest
Xamarin.Plugin.SharedTransitions : Latest

**Comment by GiampaoloGabba** [comment]
this is fixed in next release
