### ISSUE TITLE
samples and future development

### ISSUE THREAD

**Issue by vniehues** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#5]
I just recently started using your Nuget however i'm facing problems using the "Advanced shared transitions". 
Could you give us an update if you are still maintaining this project? 
And if so, can you provide a sample for the advanced transitions? 

Thanks in advance! :)

**Comment by GiampaoloGabba** [comment]
Hello, every time i want to get some time to update this plugin, something happens and i need to delay the updates :)
Luckily @jsuarezruiz  submitted some updates. I already merged two and i'm trying the third. If everything goes fine i'll will make a new nuget with the updates.

Meanwhile there is an update in the readme (made by jsuarezruiz) with a link to a working example of 
 advanced shared transitions in a collectionview
