### ISSUE TITLE
[Bug] Didn't find class "android.transition.TransitionListenerAdapter"

### ISSUE THREAD

**Issue by Martinedo** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#58]
## Bug Information

Version Number of Plugin: 2.3.0
Device Tested On: **Pixel 7.1.2, Galaxy J2 Pro 7.1.1**
Version of Xamarin: 4.8.0.1451

### Steps to reproduce the Behavior
It seam that **Android Nougat** is only affected. After calling the constructor of **SharedTransitionNavigationPage** the app crashes with: 
`java.lang.ClassNotFoundException: Didn't find class "android.transition.TransitionListenerAdapter"`

### Code snippet
On the line:
`SharedTransitionNavigationPageRenderer.addView SharedTransitionNavigationPageRenderer.java:45`

**Comment by GiampaoloGabba** [comment]
this is fixed in 2.4, its already on nuget :)
