### ISSUE TITLE
Navigate inside a ViewModel ? 

### ISSUE THREAD

**Issue by Strypper** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#60]
Anyone got an example how can I put my navigate logic inside a viewmodel ?

**Comment by GiampaoloGabba** [comment]
Hello, there is a [wiki article](https://github.com/GiampaoloGabba/Xamarin.Plugin.SharedTransitions/wiki/4.-Advanced-shared-transitions-between-collection-of-views-and-their-details-page#listview-mvvm-sample) (Listview MVVM sample) wich shows navigation inside viewmodel (using Prism).
