### ISSUE TITLE
How to set the duration?

### ISSUE THREAD

**Issue by csp04** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#61]
Is there a way to speed up the transition?

**Comment by GiampaoloGabba** [comment]
You can set the `SharedTransitionDuration` property in you `SharedTransitionNavigationPage`  or `SharedTransitionShell`

More info on [wiki](https://github.com/GiampaoloGabba/Xamarin.Plugin.SharedTransitions/wiki/2.-Navigation-configuration)
