### ISSUE TITLE
Translation animation is not working

### ISSUE THREAD

**Issue by Sumit2668** [GiampaoloGabba/Xamarin.Plugin.SharedTransitions#62]
## Hi, 
I am using this plugin, and try to implement the **Translation animation** but after implementing your code in my project but it is not working. 
It looks like 

![dog2](https://user-images.githubusercontent.com/26775231/100870211-42918700-34c4-11eb-9d53-8e871bcc46f0.gif)

please give some suggestions.

**Comment by GiampaoloGabba** [comment]
Hello, i need more informations: what's the version of Xamarin.Forms in your project?
Are us sure to have wrapped the navigation in a `SharedTransitionNavigationPage`or `SharedTransitionShell`?
Can you post your code?
